# NOTE: This file is kept for reference but NOT USED in host-only mode
# All services run directly on the host system
version: '3.8'

services:
  # OpenWebUI - Main User Interface
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: alphaomega-openwebui
    ports:
      - "${OPENWEBUI_PORT:-3000}:8080"
    volumes:
      - ./openwebui_data:/app/backend/data
      - ./pipelines:/app/backend/pipelines
    environment:
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434;http://host.docker.internal:11435
      - COMFYUI_BASE_URL=http://comfyui:8188
      - ENABLE_OLLAMA_API=true
      - WEBUI_AUTH=${WEBUI_AUTH:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - alphaomega-network

  # ComfyUI - GPU 2 (MI50 #3) - Image Generation
  comfyui:
    build:
      context: ./comfyui_bridge
      dockerfile: Dockerfile
    container_name: alphaomega-comfyui
    ports:
      - "${COMFYUI_PORT:-8188}:8188"
    volumes:
      - ./models/comfyui:/app/models
      - ./comfyui_bridge/workflows:/app/workflows
      - ./comfyui_bridge/output:/app/output
    environment:
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      - ROCR_VISIBLE_DEVICES=2
      - PYTORCH_HIP_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_mb:512
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      - alphaomega-network

networks:
  alphaomega-network:
    driver: bridge
    name: alphaomega-network

volumes:
  openwebui_data:
    driver: local
  ollama_models:
    driver: local
  comfyui_models:
    driver: local
